$c = [System.IO.File]::ReadAllText('d:\Project\Website_SV_IUH-demo\css\index.css')
$c = $c.Replace('1.125rem', '18px')
$c = $c.Replace('1.25rem', '20px')
$c = $c.Replace('1.5rem', '24px')
$c = $c.Replace('0.875rem', '14px')
$c = $c.Replace('0.85rem', '14px')
$c = $c.Replace('0.625rem', '10px')
$c = $c.Replace('0.375rem', '6px')
$c = $c.Replace('0.125rem', '2px')
$c = $c.Replace('0.75rem', '12px')
$c = $c.Replace('0.5rem', '8px')
$c = $c.Replace('0.25rem', '4px')
$c = $c.Replace('0.4rem', '6px')
$c = $c.Replace('0.9rem', '14px')
$c = $c.Replace('0.8rem', '13px')
$c = $c.Replace('2rem', '32px')
[System.IO.File]::WriteAllText('d:\Project\Website_SV_IUH-demo\css\index.css', $c)
Write-Host 'Done'
